// src/lib/components/UrlInput.svelte
<script lang="ts">
	import { Button } from '$lib/components/ui/button';
	import { Input } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';

	type Props = {
		onsubmit: (url: string, title: string) => void;
	};

	const { onsubmit }: Props = $props();

	let url = $state('');
	let title = $state('');
	let error = $state('');

	function handleSubmit(event: SubmitEvent) {
		event.preventDefault();
		if (!url.trim()) {
			error = 'Please enter a URL';
			return;
		}
		if (!url.trim().endsWith('.m3u8')) {
			error = 'URL must end with .m3u8';
			return;
		}
		onsubmit(url.trim(), title.trim() || 'Untitled');
		url = '';
		title = '';
		error = '';
	}
</script>

<form class="w-full" onsubmit={handleSubmit}>
	<div class="mb-4 grid gap-1.5">
		<Label for="title">Title (optional)</Label>
		<Input id="title" type="text" placeholder="Video title" bind:value={title} />
	</div>

	<div class="grid gap-1.5">
		<Label for="url">M3U8 URL</Label>
		<div class="flex items-stretch gap-2">
			<Input
				id="url"
				type="url"
				placeholder="https://example.com/video.m3u8"
				required
				bind:value={url}
				oninput={() => (error = '')}
				class="flex-1"
			/>
			<Button type="submit">Play</Button>
		</div>
		{#if error}
			<p class="text-sm text-destructive">{error}</p>
		{/if}
	</div>
</form>

// src/components/UrlInput.tsx
import React, { useState } from 'react';

interface UrlInputProps {
  onSubmit: (url: string, title: string) => void;
}

const UrlInput: React.FC<UrlInputProps> = ({ onSubmit }) => {
  const [url, setUrl] = useState('');
  const [title, setTitle] = useState('');
  const [error, setError] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!url.trim()) {
      setError('Please enter a URL');
      return;
    }

    if (!url.trim().endsWith('.m3u8')) {
      setError('URL must end with .m3u8');
      return;
    }

    onSubmit(url.trim(), title.trim() || 'Untitled');
    setUrl('');
    setTitle('');
    setError('');
  };

  return (
    <form onSubmit={handleSubmit} className="w-full">
      <div className="mb-4">
        <label htmlFor="title" className="block text-sm font-medium mb-1">
          Title (optional)
        </label>
        <input
          type="text"
          id="title"
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          placeholder="Video title"
          className="w-full px-4 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500 dark:text-white"
        />
      </div>
      
      <div className="mb-2">
        <label htmlFor="url" className="block text-sm font-medium mb-1">
          M3U8 URL
        </label>
        <div className="flex items-center">
          <input
            type="url"
            id="url"
            value={url}
            onChange={(e) => {
              setUrl(e.target.value);
              setError('');
            }}
            placeholder="https://example.com/video.m3u8"
            className="flex-1 px-4 py-2 rounded-l-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500 dark:text-white"
            required
          />
          <button
            type="submit"
            className="px-4 py-2 bg-blue-500 hover:bg-blue-600 text-white font-medium rounded-r-lg transition-colors"
          >
            Play
          </button>
        </div>
        {error && <p className="text-red-500 text-sm mt-1">{error}</p>}
      </div>
    </form>
  );
};

export default UrlInput;
