// src/lib/components/VideoPlayer.svelte
<script lang="ts">
	import { onDestroy, onMount } from 'svelte';
	import 'video.js/dist/video-js.css';

	type Props = {
		src: string;
		class?: string;
		autoPlay?: boolean;
	};

	const { src, class: className, autoPlay = false }: Props = $props();

	let host: HTMLDivElement | undefined = $state();
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	let player: any = null;

	async function init() {
		if (!host) return;
		const { default: videojs } = await import('video.js');
		const el = document.createElement('video-js');
		el.classList.add('vjs-big-play-centered');
		// eslint-disable-next-line svelte/no-dom-manipulating -- video.js owns this subtree; not part of Svelte's DOM
		host.appendChild(el);
		player = videojs(el, {
			autoplay: autoPlay,
			controls: true,
			responsive: true,
			fluid: true,
			sources: [{ src, type: 'application/x-mpegURL' }]
		});
	}

	onMount(() => {
		init();
	});

	onDestroy(() => {
		if (player) {
			player.dispose();
			player = null;
		}
	});

	$effect(() => {
		if (player) {
			player.src([{ src, type: 'application/x-mpegURL' }]);
			if (autoPlay) player.play()?.catch(() => {});
		}
	});
</script>

<div data-vjs-player class={className}>
	<div bind:this={host} class="h-full w-full overflow-hidden rounded-lg"></div>
</div>

// src/components/VideoPlayer.tsx
import React, { useEffect, useRef } from 'react';
import videojs from 'video.js';
import 'video.js/dist/video-js.css';
import type Player from 'video.js/dist/types/player';

interface VideoPlayerProps {
  src: string;
  onVideoEnd?: () => void;
  className?: string;
  autoPlay?: boolean;
}

const VideoPlayer: React.FC<VideoPlayerProps> = ({ 
  src, 
  onVideoEnd, 
  className,
  autoPlay = false 
}) => {
  const videoRef = useRef<HTMLDivElement>(null);
  const playerRef = useRef<Player | null>(null);

  useEffect(() => {
    // Make sure Video.js player is only initialized once
    if (!playerRef.current && videoRef.current) {
      // Initialize the Video.js player
      const videoElement = document.createElement('video-js');
      videoElement.classList.add('vjs-big-play-centered');
      videoRef.current.appendChild(videoElement);

      playerRef.current = videojs(videoElement, {
        autoplay: autoPlay,
        controls: true,
        responsive: true,
        fluid: true,
        sources: [{
          src,
          type: 'application/x-mpegURL'
        }]
      });

      // Add event listener for video end
      if (onVideoEnd) {
        playerRef.current.on('ended', onVideoEnd);
      }
    } else if (playerRef.current) {
      // Update the player source if it already exists
      playerRef.current.src([{
        src,
        type: 'application/x-mpegURL'
      }]);
    }

    return () => {
      // Dispose the Video.js player when component unmounts
      if (playerRef.current) {
        playerRef.current.dispose();
        playerRef.current = null;
      }
    };
  }, [src, onVideoEnd, autoPlay]);

  return (
    <div data-vjs-player className={className}>
      <div ref={videoRef} className="w-full h-full rounded-lg overflow-hidden" />
    </div>
  );
};

export default VideoPlayer;
